"""Contract-first models for the personal research platform migration."""

from .agent_contracts import (
    AgentOutputEnvelope,
    AgentOutputSection,
    AgentOutputType,
    AnalystNote,
    ConfidenceLevel,
    EvidenceRef,
    InvestmentThesis,
    ThesisScenario,
    TradeDirection,
    TradeHorizon,
    TradeSignal,
)
from .backtest_contracts import (
    BacktestConfig,
    BacktestMetrics,
    BacktestResult,
    BacktestRoundTrip,
    BacktestTrade,
    BacktestWarning,
    BacktestWarningSeverity,
    EquityPoint,
    ExecutionConfig,
    validate_signal_timing,
)
from .company_profile import CompanyProfile, build_company_profile
from .data_contracts import (
    AssetClass,
    DataProvenance,
    DataProvider,
    FundamentalSnapshot,
    InstrumentIdentity,
    NewsItem,
    PriceBar,
)
from .data_health import build_cache_data_health
from .game_approvals import (
    GameApprovalDigest,
    GameApprovalKind,
    GameApprovalMatch,
    GameApprovalRecord,
    GameCompanyMatchStatus,
    JsonGameApprovalStore,
    make_approval_id,
    match_game_approval,
)
from .game_opportunity import (
    GameOpportunityFactor,
    GameOpportunityFactorStatus,
    GameOpportunityLevel,
    GameOpportunitySnapshot,
    build_game_opportunity_board,
    build_game_opportunity_snapshot,
)
from .game_opportunity_history import (
    GameOpportunityEvent,
    GameOpportunityEventSeverity,
    GameOpportunityEventType,
    GameOpportunityHistoryView,
    GameOpportunityTrackingBatch,
    GameOpportunityTrackingResult,
    JsonGameOpportunityHistory,
    build_game_opportunity_history_view,
    compare_game_opportunities,
    record_game_opportunity_board,
)
from .game_universe import (
    GameBusinessEntity,
    GameCatalyst,
    GameCatalystCategory,
    GameCatalystStatus,
    GameCatalystView,
    GameCompanyProfile,
    GameEntityRole,
    GameEvidence,
    GameEvidenceType,
    GameProduct,
    GameProductStatus,
    GameResearchSnapshot,
    build_game_research_snapshot,
    list_game_universe_symbols,
)
from .narrative_provider import (
    NarrativeMode,
    NarrativeProviderError,
    NarrativeProviderUnavailableError,
    OpenAIResearchNarrativeProvider,
    ResearchNarrativeContext,
    ResearchNarrativeProvider,
)
from .nppa_provider import NppaApprovalProvider, NppaProviderError
from .report_workspace import build_report_workspace, render_archived_report
from .research_jobs import (
    LocalResearchJobRunner,
    ManualSignalRequest,
    ResearchDataProvider,
    ResearchJob,
    ResearchJobRequest,
    ResearchJobStatus,
    resolve_data_provider,
)
from .research_readiness import (
    ReadinessItemStatus,
    ReadinessStatus,
    ResearchReadiness,
    ResearchReadinessItem,
    build_research_readiness,
)
from .risk_contracts import (
    RiskDecision,
    RiskLimitBreach,
    RiskPolicy,
    RiskReview,
    RiskRuleResult,
    RiskSeverity,
    evaluate_basic_risk,
)
from .run_archive import JsonResearchRunArchive, ResearchRunArchive, ResearchRunSummary
from .tushare_provider import (
    TushareDataUnavailableError,
    TushareProProvider,
    canonical_tushare_symbol,
    supports_tushare_symbol,
)
from .valuation_context import ValuationContext, ValuationMetricContext, build_valuation_context
from .watchlist import JsonWatchlistStore, WatchlistEntry
from .watchlist_board import build_watchlist_board
from .watchlist_refresh import (
    WatchlistRefreshBatch,
    WatchlistRefreshOutcome,
    WatchlistRefreshRequest,
    execute_watchlist_refresh,
    submit_watchlist_refresh,
)

__all__ = [
    "AgentOutputEnvelope",
    "AgentOutputSection",
    "AgentOutputType",
    "AnalystNote",
    "AssetClass",
    "BacktestConfig",
    "BacktestMetrics",
    "BacktestResult",
    "BacktestRoundTrip",
    "BacktestTrade",
    "BacktestWarning",
    "BacktestWarningSeverity",
    "build_cache_data_health",
    "build_company_profile",
    "build_game_research_snapshot",
    "build_game_opportunity_board",
    "build_game_opportunity_snapshot",
    "build_game_opportunity_history_view",
    "GameApprovalDigest",
    "GameApprovalKind",
    "GameApprovalMatch",
    "GameApprovalRecord",
    "GameCompanyMatchStatus",
    "GameOpportunityFactor",
    "GameOpportunityFactorStatus",
    "GameOpportunityLevel",
    "GameOpportunitySnapshot",
    "GameOpportunityEvent",
    "GameOpportunityEventSeverity",
    "GameOpportunityEventType",
    "GameOpportunityHistoryView",
    "GameOpportunityTrackingBatch",
    "GameOpportunityTrackingResult",
    "GameBusinessEntity",
    "GameCatalyst",
    "GameCatalystCategory",
    "GameCatalystStatus",
    "GameCatalystView",
    "GameCompanyProfile",
    "GameEntityRole",
    "GameEvidence",
    "GameEvidenceType",
    "GameProduct",
    "GameProductStatus",
    "GameResearchSnapshot",
    "list_game_universe_symbols",
    "make_approval_id",
    "match_game_approval",
    "compare_game_opportunities",
    "record_game_opportunity_board",
    "build_report_workspace",
    "build_research_readiness",
    "build_watchlist_board",
    "build_valuation_context",
    "canonical_tushare_symbol",
    "CompanyProfile",
    "ConfidenceLevel",
    "DataProvider",
    "DataProvenance",
    "EquityPoint",
    "EvidenceRef",
    "ExecutionConfig",
    "FundamentalSnapshot",
    "InstrumentIdentity",
    "InvestmentThesis",
    "JsonGameApprovalStore",
    "JsonGameOpportunityHistory",
    "JsonResearchRunArchive",
    "JsonWatchlistStore",
    "LocalResearchJobRunner",
    "ManualSignalRequest",
    "NarrativeMode",
    "NarrativeProviderError",
    "NarrativeProviderUnavailableError",
    "NewsItem",
    "NppaApprovalProvider",
    "NppaProviderError",
    "OpenAIResearchNarrativeProvider",
    "PriceBar",
    "ResearchDataProvider",
    "ResearchJob",
    "ResearchJobRequest",
    "ResearchJobStatus",
    "ResearchNarrativeContext",
    "ResearchNarrativeProvider",
    "ResearchRunArchive",
    "ResearchReadiness",
    "ResearchReadinessItem",
    "ResearchRunSummary",
    "resolve_data_provider",
    "supports_tushare_symbol",
    "render_archived_report",
    "ReadinessItemStatus",
    "ReadinessStatus",
    "RiskDecision",
    "RiskLimitBreach",
    "RiskPolicy",
    "RiskReview",
    "RiskRuleResult",
    "RiskSeverity",
    "ThesisScenario",
    "TradeDirection",
    "TradeHorizon",
    "TradeSignal",
    "TushareDataUnavailableError",
    "TushareProProvider",
    "ValuationContext",
    "ValuationMetricContext",
    "WatchlistRefreshBatch",
    "WatchlistRefreshOutcome",
    "WatchlistRefreshRequest",
    "WatchlistEntry",
    "evaluate_basic_risk",
    "execute_watchlist_refresh",
    "submit_watchlist_refresh",
    "validate_signal_timing",
]
