"""Standalone configuration page for sectors, universes, and research periods."""

SETTINGS_HTML = r"""<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>研究配置</title><style>
:root{font-family:Inter,"Microsoft YaHei",system-ui,sans-serif;color:#17232c;background:#f3f6f7}*{box-sizing:border-box}body{margin:0}button,input,select{font:inherit}.shell{max-width:1180px;margin:auto;padding:28px}.top{display:flex;align-items:center;justify-content:space-between;margin-bottom:22px}.eyebrow{color:#39706e;font-size:12px;font-weight:750;letter-spacing:.08em}.top h1{margin:4px 0 0}.back{color:#176f6c;text-decoration:none;font-weight:700}.panel{background:#fff;border:1px solid #d7e1e3;border-radius:8px;margin:14px 0;overflow:hidden}.panel-head{display:flex;align-items:center;justify-content:space-between;padding:18px 20px;border-bottom:1px solid #e3eaec}.panel-head h2{font-size:17px;margin:0}.body{padding:20px}.hint,.meta{color:#64747d;font-size:13px;line-height:1.7}.row{display:grid;grid-template-columns:80px 140px 1fr 1fr 44px;gap:10px;align-items:center;margin-bottom:10px}.period-row{display:grid;grid-template-columns:110px 1fr 180px 44px;gap:10px;margin-bottom:10px}input,select{width:100%;padding:9px 10px;border:1px solid #bdcdd1;border-radius:5px;background:#fff}.check{width:18px;height:18px}.actions{display:flex;gap:10px;flex-wrap:wrap}.primary{background:#176f6c;color:white;border:0}.danger{color:#aa4c32}.button,button{padding:9px 14px;border:1px solid #aebfc3;border-radius:5px;background:#fff;cursor:pointer;font-weight:650}.status{padding:12px 14px;background:#edf5f4;border-left:3px solid #176f6c;margin-top:14px;white-space:pre-wrap}.status.error{background:#fff1ec;border-color:#ba5a3c}.chips{display:flex;gap:6px;flex-wrap:wrap}.chip{font-size:12px;padding:4px 8px;border-radius:999px;background:#e8f4f3;color:#176f6c}.results{max-height:420px;overflow:auto;border:1px solid #e3eaec;margin-top:14px}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:9px 12px;border-bottom:1px solid #e8edef}th{position:sticky;top:0;background:#f8fafb}.empty{padding:24px;color:#64747d;text-align:center}@media(max-width:800px){.row,.period-row{grid-template-columns:1fr}.shell{padding:16px}}
</style></head><body><main class="shell">
<div class="top"><div><div class="eyebrow">个人股票投研</div><h1>研究配置</h1></div><a class="back" href="/">返回研究驾驶舱</a></div>
<section class="panel"><div class="panel-head"><h2>数据策略</h2></div><div class="body">
<label>优先数据源<select id="provider"><option value="auto">自动（A/H/BJ 优先 Tushare Pro）</option><option value="tushare">仅 Tushare Pro</option><option value="yfinance">Yahoo Finance</option></select></label>
<p class="hint">密钥仅由服务端环境变量读取，不会出现在此页面或 API 响应中。</p></div></section>
<section class="panel"><div class="panel-head"><h2>自选股板块</h2><button id="addSector">新增板块</button></div><div class="body">
<p class="hint">按 Tushare 概念名称匹配关键词并合并成分股。包含/排除代码以逗号分隔；同步只新增和合并板块，不会删除已有自选股。</p>
<div class="row meta"><span>启用</span><span>板块名称</span><span>概念关键词</span><span>包含 / 排除代码</span><span></span></div><div id="sectors"></div></div></section>
<section class="panel"><div class="panel-head"><h2>研究数据周期</h2><button id="addPeriod">新增周期</button></div><div class="body">
<p class="hint">默认周期会用于单股研究与批量刷新；最多 3650 天，后续可继续增加预设。</p><div class="period-row meta"><span>默认</span><span>名称</span><span>天数</span><span></span></div><div id="periods"></div></div></section>
<div class="actions"><button id="save" class="primary">保存配置</button><button id="preview">发现并预览</button><button id="sync" class="primary">同步到自选股</button></div>
<div id="status" class="status">正在读取配置…</div><div id="results"></div>
</main><script>
const $=id=>document.getElementById(id);let settings=null;const split=v=>v.split(/[,，\n]/).map(x=>x.trim()).filter(Boolean);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function sectorRow(rule){const row=document.createElement('div');row.className='row';row.dataset.id=rule.id;row.innerHTML='<input class="check enabled" type="checkbox" '+(rule.enabled?'checked':'')+'><input class="name" value="'+esc(rule.name)+'"><input class="keywords" value="'+esc(rule.keywords.join('，'))+'"><div><input class="includes" placeholder="包含代码" value="'+esc(rule.explicit_includes.join(','))+'"><input class="excludes" placeholder="排除代码" value="'+esc(rule.explicit_excludes.join(','))+'" style="margin-top:5px"></div><button class="danger remove">×</button>';row.querySelector('.remove').onclick=()=>row.remove();return row}
function periodRow(item){const row=document.createElement('div');row.className='period-row';row.dataset.id=item.id;row.innerHTML='<label><input class="default-period" type="radio" name="defaultPeriod" '+(settings.default_period_id===item.id?'checked':'')+'> 默认</label><input class="period-name" value="'+esc(item.name)+'"><input class="days" type="number" min="1" max="3650" value="'+item.days+'"><button class="danger remove">×</button>';row.querySelector('.remove').onclick=()=>row.remove();return row}
function render(){ $('provider').value=settings.preferred_data_provider;$('sectors').replaceChildren(...settings.sector_rules.map(sectorRow));$('periods').replaceChildren(...settings.period_presets.map(periodRow));$('status').textContent='配置已读取。Tushare Token：服务端'+(settings.tushare_configured?'已配置':'未配置')+'。'}
function collect(){const sectors=[...$('sectors').children].map((row,i)=>({id:row.dataset.id||'sector-'+(i+1),name:row.querySelector('.name').value,enabled:row.querySelector('.enabled').checked,keywords:split(row.querySelector('.keywords').value),explicit_includes:split(row.querySelector('.includes').value),explicit_excludes:split(row.querySelector('.excludes').value)}));const periods=[...$('periods').children].map((row,i)=>({id:row.dataset.id||'period-'+(i+1),name:row.querySelector('.period-name').value,days:Number(row.querySelector('.days').value)}));const selected=[...$('periods').children].find(row=>row.querySelector('.default-period').checked);return {version:1,preferred_data_provider:$('provider').value,default_period_id:selected?.dataset.id||periods[0]?.id,sector_rules:sectors,period_presets:periods}}
async function save(){const res=await fetch('/api/research-settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(collect())});const body=await res.json();if(!res.ok)throw new Error(body.error||'保存失败');settings={...body.settings,tushare_configured:body.tushare_configured};$('status').className='status';$('status').textContent='配置已保存。';return body}
function show(result){const stocks=result.stocks||[];$('results').className='results';$('results').innerHTML=stocks.length?'<table><thead><tr><th>代码</th><th>公司</th><th>板块</th><th>匹配概念</th></tr></thead><tbody>'+stocks.map(x=>'<tr><td>'+esc(x.symbol)+'</td><td>'+esc(x.name||'-')+'</td><td><div class="chips">'+x.sector_names.map(v=>'<span class="chip">'+esc(v)+'</span>').join('')+'</div></td><td>'+esc(x.matched_concepts.join('、')||'手工包含')+'</td></tr>').join('')+'</tbody></table>':'<div class="empty">没有发现符合当前规则的股票。</div>'}
async function discover(sync){await save();$('status').textContent=sync?'正在发现并同步，请稍候…':'正在读取 Tushare 概念与成分…';const res=await fetch(sync?'/api/universe-sync':'/api/universe-preview',{method:'POST'});const body=await res.json();if(!res.ok)throw new Error(body.error||'发现失败');show(body.discovery);$('status').className='status';$('status').textContent=(sync?'已同步 ':'已发现 ')+body.discovery.stocks.length+' 只股票'+(sync?'；当前自选股 '+body.watchlist_total+' 只。':'。')+(body.discovery.warnings.length?'\n部分警告：'+body.discovery.warnings.slice(0,3).join('；'):'')}
function fail(e){$('status').className='status error';$('status').textContent=e.message}
$('addSector').onclick=()=>{const id='sector-'+Date.now();$('sectors').append(sectorRow({id,name:'新板块',enabled:true,keywords:[],explicit_includes:[],explicit_excludes:[]}))};$('addPeriod').onclick=()=>{const id='period-'+Date.now();settings.default_period_id='';$('periods').append(periodRow({id,name:'自定义周期',days:365}))};$('save').onclick=()=>save().catch(fail);$('preview').onclick=()=>discover(false).catch(fail);$('sync').onclick=()=>discover(true).catch(fail);
fetch('/api/research-settings').then(r=>r.json()).then(x=>{settings={...x.settings,tushare_configured:x.tushare_configured};render()}).catch(fail);
</script></body></html>"""
